openapi: 3.0.1
info:
  title: Test
  description: Test project documentation
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: kuamatzin@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 2.0.0
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
servers:
  - url: 'https://us-central1-wrabbitignys.cloudfunctions.net'
  - url: 'http://localhost:5000/wrabbitignys/us-central1'

tags:
  - name: auth
    description: Authentication service
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
  - name: accounts
    description: Accounts service
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
paths:
  '/auth':
    post:
      security: []
      tags:
        - auth
      summary: Signup
      description: Signup
      operationId: signup
      requestBody:
        description: Sign up the user and get the token
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Signup'
        required: true
      responses:
        '405':
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
  '/auth/login':
    post:
      security: []
      tags:
        - auth
      summary: Login
      description: Login
      operationId: login
      requestBody:
        description: Get the token
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
        required: true
      responses:
        '405':
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
  '/auth/reset':
    post:
      security: []
      tags:
        - auth
      summary: Reset password
      description: Reset password
      operationId: reset
      requestBody:
        description: Reset password
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Reset'
        required: true
      responses:
        '405':
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
  '/auth/change':
    post:
      tags:
        - auth
      summary: Change password
      description: Change password
      operationId: change
      requestBody:
        description: Reset password
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Change'
        required: true
      responses:
        '405':
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
  '/accounts':
    get:
      tags:
        - accounts
      summary: Get account details
      description: Retrieve account details
      operationId: getAccount
      responses:
        '200':
          description: Success
          content: {}
  '/accounts/all':
    get:
      tags:
        - accounts
      summary: Get account details
      description: Retrieve account details
      operationId: getAllAccounts
      responses:
        '200':
          description: Success
          content: {}
  '/transactions/received':
    get:
      tags:
        - transactions
      summary: Get received transactions
      description: Get received transactions
      operationId: getReceivedTransactions
      responses:
        '200':
          description: Success
          content: {}
  '/transactions/sent':
    get:
      tags:
        - transactions
      summary: Get sent transactions
      description: Get sent transactions
      operationId: getSentTransactions
      responses:
        '200':
          description: Success
          content: {}
  'transactions':
    post:
      tags:
        - transactions
      summary: Make a transaction between two accounts
      description: Transfer money from auth account to toAccount
      operationId: transferMoney
      requestBody:
        description: Tower object that needs to be added
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
        required: true
      responses:
        '405':
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
components:
  schemas:
    # Reset Schema
    Reset:
      type: object
      properties:
        email:
          type: string
    # End Reset Schema
    # Change Schema
    Change:
      type: object
      properties:
        password:
          type: string
    # End Change Schema
    # Signup Schema
    Signup:
      type: object
      properties:
        fullName:
          type: string
        email:
          type: string
        password:
          type: string
        confirmPassword:
          type: string
        balance:
          type: integer
    # End Signup Schema
    # Login Schema
    Login:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    # End Login Schema
    Transaction:
      type: object
      properties:
        toAccount:
          type: string
        amount:
          type: number
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
